/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    model: THREE.Mesh
  }
  materials: {
    model: THREE.MeshStandardMaterial
  }
}

const GLB_URL = 'https://raw.githubusercontent.com/Iresh-Nimantha/test-img-upload/main/base_basic_pbr.glb'

const context = createContext<any>(null)

export function Instances({ children, ...props }: { children: React.ReactNode }) {
  const { nodes } = useGLTF(GLB_URL) as unknown as GLTFResult
  const instances = useMemo(
    () => ({
      Model: nodes.model,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: any) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props: any) {
  const instances = useContext(context)
  if (!instances) return null
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <instances.Model name="model" userData={{ name: 'model' }} />
      </group>
    </group>
  )
}

useGLTF.preload(GLB_URL)
